name: Docker Inventory Service Image CI/CD

on:
  push:
    branches: [ "feature/ci-cd-setup" ]
  pull_request:
    branches: [ "feature/ci-cd-setup" ]

jobs:
  build-push-inventoryservice:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build inventory service image
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push inventory service image 
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: | 
        docker compose -f docker-compose.yml build inventoryservice
        docker compose -f docker-compose.yml push inventoryservice

  deploy-inventoryservice:
    needs: build-push-inventoryservice
    runs-on: ubuntu-latest

    steps:
    - name: Deploy inventory service image
      uses: appleboy/ssh-action@v1.2.2
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker pull ${{ secrets.DOCKER_USERNAME }}/inventoryservice:latest
          docker compose -f docker-compose-deploy.yml up -d inventoryservice